name: Qrowdr
favicon: null
layout_spectrum: 0.8706330214627087
typography_spectrum: 0.3880003886297345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6132052422035486
  lightness: 0.19210574333555996
  saturation: 0.6036183559335768
  rhythmicContrast: 0.09025604673661292
purpose: []
